name       : streamlink-twitch-gui
version    : 1.4.1
release    : 5
source     :
    - git|https://github.com/streamlink/streamlink-twitch-gui.git : v1.4.1
license    : MIT
component  : network.web
summary    : Browse Twitch.tv and watch streams in your videoplayer of choice
description: |
    Browse Twitch.tv and watch streams in your videoplayer of choice. GNOME MPV, MPV and VLC are supported.
networking : yes
strip      : no
debug      : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - yarn
rundeps    :
    - streamlink
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-gnome-mpv-as-an-option-for-linux.patch
    %patch -p1 < $pkgfiles/0001-linux-use-python3-by-default.patch
    %patch -p1 < $pkgfiles/0001-pass-allow-root-to-bower-install.patch
    %patch -p1 < $pkgfiles/0001-Set-player-passthrough-as-the-default-player-input-m.patch
build      : |
    # workaround for yarn global not working
    export PATH=$workdir/node_modules/.bin:$PATH

    yarn add bower grunt-cli
    yarn install

    grunt webpack:prod
    grunt dist
install    : |
    # Install .desktop file
    install -Dm00644 $pkgfiles/streamlink-twitch-gui.desktop $installdir/usr/share/applications/streamlink-twitch-gui.desktop

    # Copy to our final destination
    install -dm00755 $installdir/usr/share/streamlink-twitch-gui/
    cp -R $workdir/build/releases/streamlink-twitch-gui/linux64/* $installdir/usr/share/streamlink-twitch-gui/

    # Install icons
    for size in 16 32 48 64 128 256; do
    install -Dm00644 $workdir/build/releases/streamlink-twitch-gui/linux64/icons/icon-$size.png \
      $installdir/usr/share/icons/hicolor/${size}x${size}/apps/streamlink-twitch-gui.png
    done

    # Remove janky scripts we don't need
    rm $installdir/usr/share/streamlink-twitch-gui/*.sh

    # Symlink the binary to $PATH
    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/streamlink-twitch-gui/streamlink-twitch-gui $installdir/usr/bin/streamlink-twitch-gui
